// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA955URPGmkksRjv7pyNTJyW8Atzmdsrvs',
    appId: '1:116195211340:web:2d44593a4b20f30314dce9',
    messagingSenderId: '116195211340',
    projectId: 'telemonitor',
    authDomain: 'telemonitor.firebaseapp.com',
    storageBucket: 'telemonitor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfVCl9w20xbWXv0A_zYz01K4RGvQnkJ_k',
    appId: '1:116195211340:android:14050ee405729ba714dce9',
    messagingSenderId: '116195211340',
    projectId: 'telemonitor',
    storageBucket: 'telemonitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNiv1NTolSFH5tHnClXwVPxMald3GM-6g',
    appId: '1:116195211340:ios:e2a960911838bed814dce9',
    messagingSenderId: '116195211340',
    projectId: 'telemonitor',
    storageBucket: 'telemonitor.firebasestorage.app',
    iosBundleId: 'com.example.telemonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNiv1NTolSFH5tHnClXwVPxMald3GM-6g',
    appId: '1:116195211340:ios:e2a960911838bed814dce9',
    messagingSenderId: '116195211340',
    projectId: 'telemonitor',
    storageBucket: 'telemonitor.firebasestorage.app',
    iosBundleId: 'com.example.telemonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA955URPGmkksRjv7pyNTJyW8Atzmdsrvs',
    appId: '1:116195211340:web:e35cb48a6d77387614dce9',
    messagingSenderId: '116195211340',
    projectId: 'telemonitor',
    authDomain: 'telemonitor.firebaseapp.com',
    storageBucket: 'telemonitor.firebasestorage.app',
  );
}
